openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /users:
    post:
      tags:
        - user-controller-impl
      operationId: createUser1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorDTO'
        "201":
          description: Created
components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        code:
          type: integer
          format: int32
        description:
          type: string
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Wade"
        email:
          type: string
          example: "john@test.com"
        password:
          type: string
          example: "password1"
        createdTime:
          type: string
          format: date-time
        updatedTime:
          type: string
          format: date-time
